config/routes.rb
Shoppe::Engine.routes.draw do
  get 'attachment/:id/:filename.:extension' => 'attachments#show'

  resources :customers do
    post :search, :on => :collection
    resources :addresses
  end

  resources :blogposts
  resources :currencies
  resources :purchased_items

  resources :product_categories do
    resources :localisations, controller: "product_category_localisations"
  end
  resources :products do
    resources :variants
    resources :localisations, controller: "product_localisations"
    collection do
      get :import
      post :import
    end
  end
  resources :orders do
    collection do
      post :search
      post :submit_to_admin
      post :mass_process
    end
    member do
      delete :remove_order_purchased_item
      post :add_order_purchased_item
      post :assign_to_me
      post :accept
      post :reject
      post :ship
      get :despatch_note
      post :archive
      post :calculate_commission
    end
    resources :payments, :only => [:create, :destroy] do
      match :refund, :on => :member, :via => [:get, :post]
    end
  end
  resources :stock_level_adjustments, :only => [:index, :create]
  resources :delivery_services do
    resources :delivery_service_prices
  end
  resources :tax_rates
  resources :users do
    collection do
      get :sales_reps
      get :my_account
    end
  end
  resources :countries
  resources :attachments, :only => :destroy

  get 'settings'=> 'settings#edit'
  post 'settings' => 'settings#update'

  get 'permissions'=> 'permissions#edit', as: "edit_permissions"
  patch 'permissions' => 'permissions#update', as: "update_permissions"

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'authenticate' => 'sessions#second_authentication', as: "second_authentication"
  post 'perform_second_authentication' => 'sessions#perform_second_authentication', as: "perform_second_authentication"

  match 'login/reset' => 'sessions#reset', :via => [:get, :post]

  delete 'logout' => 'sessions#destroy'
  root :to => 'dashboard#home'
end

app/models/shoppe/address.rb
module Shoppe
  class Address < ActiveRecord::Base

    # An array of all the available types for an address
    TYPES = ["billing", "delivery"]

    # Set the table name
    self.table_name = "shoppe_addresses"
    
    # The customer which this address should be linked to
    # 
    # @return [Shoppe::Customer]
    belongs_to :customer, :class_name => "Shoppe::Customer"
    
    # The order which this address should be linked to
    # 
    # @return [Shoppe::Order]
    belongs_to :order, :class_name => "Shoppe::Order"

    # The country which this address should be linked to
    #
    # @return [Shoppe::Country]
    belongs_to :country, :class_name => "Shoppe::Country"

    # Validations
    validates :address_type, :presence => true, :inclusion => {:in => TYPES}
    validates :address1, :presence => true
    validates :address3, :presence => true
    validates :address4, :presence => true
    validates :postcode, :presence => true
    validates :country, :presence => true

    # All addresses ordered by their id asending
    scope :ordered, -> { order(:id => :desc)}
    scope :default, -> { where(default: true)}
    scope :billing, -> { where(address_type: "billing")}
    scope :delivery, -> { where(address_type: "delivery")}

    def full_address
      [address1, address2, address3, address4, postcode, country.try(:name)].join(", ")
    end

  end
end

app/models/shoppe/attachment.rb
module Shoppe
  class Attachment < ActiveRecord::Base

    # Set the table name
    self.table_name = "shoppe_attachments"

    # Mount the Carrierwave uploader
    mount_uploader :file, AttachmentUploader

    # Relationships
    belongs_to :parent, :polymorphic => true

    # Validations
    validates :file_name, :presence => true
    validates :file_type, :presence => true
    validates :file_size, :presence => true
    validates :file, :presence => true
    validates :token, :presence => true, :uniqueness => true

    # All attachments should have a token assigned to this
    before_validation { self.token = SecureRandom.uuid if self.token.blank? }

    # Set the appropriate values in the model
    before_validation do
      if self.file
        self.file_name = self.file.filename if self.file_name.blank?
        self.file_type = self.file.content_type if self.file_type.blank?
        self.file_size = self.file.size if self.file_size.blank?
      end
    end

    # Return the attachment for a given role
    def self.for(role)
      self.where(:role => role).first
    end

    # Return the path to the attachment
    def path
      file.url
    end

    # Is the attachment an image?
    def image?
      file_type.match(/\Aimage\//).present?
    end
    
  end
end

app/models/shoppe/blogpost.rb
module Shoppe
  class Blogpost < ActiveRecord::Base

    self.table_name = "shoppe_blogposts"

    belongs_to :author, class_name: "Shoppe::User", foreign_key: "author_id"

    has_attached_file :featured_image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/missing.png"
    validates_attachment_content_type :featured_image, content_type: /\Aimage\/.*\Z/

    validates :title, :short_description, :status, :featured_image, presence: true

    scope :published, -> { where(status: "published").order(published_at: :desc)}

  end
end

app/models/shoppe/commission.rb
module Shoppe
  class Commission < ActiveRecord::Base

    self.table_name = "shoppe_commissions"

    belongs_to :user, class_name: "Shoppe::User", foreign_key: "user_id"
    belongs_to :order, class_name: "Shoppe::Order", foreign_key: "order_id"
    belongs_to :order_purchased_item, class_name: "Shoppe::OrderPurchasedItem", foreign_key: "order_purchased_item_id"

    validates :commission_type, :commission_amount, :user_id, :order_id, presence: true

    scope :published, -> { where(status: "published").order(published_at: :desc)}
  end
end

app/models/shoppe/country.rb
module Shoppe
  
  # The Shoppe::Country model stores countries which can be used for delivery & billing
  # addresses for orders.
  #
  # You can use the Shoppe::CountryImporter to import a pre-defined list of countries 
  # into your database. This automatically happens when you run the 'shoppe:setup' 
  # rake task.
  
  class Country < ActiveRecord::Base
    
    self.table_name = 'shoppe_countries'
    
    # All orders which have this country set as their billing country
    has_many :billed_orders, :dependent => :restrict_with_exception, :class_name => 'Shoppe::Order', :foreign_key => 'billing_country_id'
    
    # All orders which have this country set as their delivery country
    has_many :delivered_orders, :dependent => :restrict_with_exception, :class_name => 'Shoppe::Order', :foreign_key => 'delivery_country_id'
    
    # All countries ordered by their name asending
    scope :ordered, -> { order(:name => :asc) }
    
    # Validations
    validates :name, :presence => true
    
  end
end

app/models/shoppe/currency.rb
module Shoppe
  class Currency < ActiveRecord::Base

    self.table_name = "shoppe_currencies"

    validates :code, :base_multiplier, presence: true

    def self.sync_currencies
      fx = OpenExchangeRates::Rates.new
      self.all.each do |c|
        c.update_attributes(base_multiplier: fx.exchange_rate(from: "CAD", to: c.code))
      end
    end

  end
end

app/models/shoppe/customer.rb
module Shoppe
  class Customer < ActiveRecord::Base

    self.table_name = "shoppe_customers"

    has_many :addresses, :dependent => :restrict_with_exception, :class_name => "Shoppe::Address"

    has_many :orders, :dependent => :restrict_with_exception, :class_name => "Shoppe::Order"

    has_many :sold_items, :class_name => "Shoppe::PurchasedItem", foreign_key: "shoppe_customer_id"

    # Validations
    validates :email, :presence => true, :uniqueness => true, :format => {:with => /\A\b[A-Z0-9\.\_\%\-\+]+@(?:[A-Z0-9\-]+\.)+[A-Z]{2,6}\b\z/i}

    has_attached_file :customer_identification, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/missing.png"
    validates_attachment_content_type :customer_identification, content_type: /\Aimage\/.*\Z/

    # All customers ordered by their ID desending
    scope :ordered, -> { order(:id => :desc)}

    # The name of the customer in the format of "Company (First Last)" or if they don't have
    # company specified, just "First Last".
    #
    # @return [String]
    def name
      company.blank? ? full_name : "#{company} (#{full_name})"
    end

    # The full name of the customer created by concatinting the first & last name
    #
    # @return [String]
    def full_name
      "#{first_name} #{last_name}"
    end

    def self.ransackable_attributes(auth_object = nil)
      ["id", "first_name", "last_name", "company", "email", "phone", "mobile"] + _ransackers.keys
    end

    def self.ransackable_associations(auth_object = nil)
      []
    end

  end
end

app/models/shoppe/delivery_service.rb
module Shoppe
  class DeliveryService < ActiveRecord::Base
  
    self.table_name = 'shoppe_delivery_services'

    # Validations
    validates :name, :presence => true
    validates :courier, :presence => true
  
    # Orders which are assigned to this delivery service
    has_many :orders, :dependent => :restrict_with_exception, :class_name => 'Shoppe::Order'
    
    # Prices for the different levels of service within this delivery service
    has_many :delivery_service_prices, :dependent => :destroy, :class_name => 'Shoppe::DeliveryServicePrice'
  
    # All active delivery services
    scope :active, -> { where(:active => true)}
    
    # Returns a tracking URL for the passed order
    #
    # @param order [Shoppe::Order]
    # @return [String] the full URL for the order.
    def tracking_url_for(order)
      return nil if self.tracking_url.blank?
      tracking_url = self.tracking_url.dup
      tracking_url.gsub!("{{consignment_number}}", CGI.escape(order.consignment_number.to_s))
      tracking_url.gsub!("{{delivery_postcode}}", CGI.escape(order.delivery_postcode.to_s))
      tracking_url.gsub!("{{billing_postcode}}", CGI.escape(order.billing_postcode.to_s))
      tracking_url
    end

  end
end

app/models/shoppe/delivery_service_price.rb
module Shoppe
  class DeliveryServicePrice < ActiveRecord::Base

    # Set the table name
    self.table_name = 'shoppe_delivery_service_prices'
  
    include Shoppe::AssociatedCountries
  
    # The delivery service which this price belongs to
    belongs_to :delivery_service, :class_name => 'Shoppe::DeliveryService'
    
    # The tax rate which should be applied
    belongs_to :tax_rate, :class_name => "Shoppe::TaxRate"
    
    # Validations
    validates :code, :presence => true
    validates :price, :numericality => true
    validates :cost_price, :numericality => true, :allow_blank => true
    validates :min_weight, :numericality => true
    validates :max_weight, :numericality => true
  
    # All prices ordered by their price ascending
    scope :ordered, -> { order(:price => :asc) }
    
    # All prices which are suitable for the weight passed.
    #
    # @param weight [BigDecimal] the weight of the order
    scope :for_weight, -> weight { where("min_weight <= ? AND max_weight >= ?", weight, weight) }
  
  end
end

app/models/shoppe/order.rb
module Shoppe
  class Order < ActiveRecord::Base

    self.table_name = 'shoppe_orders'

    # Orders can have properties
    key_value_store :properties

    # Require dependencies
    require_dependency 'shoppe/order/states'
    require_dependency 'shoppe/order/actions'
    require_dependency 'shoppe/order/billing'
    require_dependency 'shoppe/order/delivery'

    # All items which make up this order
    has_many :order_items, :dependent => :destroy, :class_name => 'Shoppe::OrderItem', :inverse_of => :order
    accepts_nested_attributes_for :order_items, :allow_destroy => true, :reject_if => Proc.new { |a| a['ordered_item_id'].blank? }

    # All products which are part of this order (accessed through the items)
    has_many :products, :through => :order_items, :class_name => 'Shoppe::Product', :source => :ordered_item, :source_type => 'Shoppe::Product'

    # The order can belong to a customer
    belongs_to :customer, :class_name => 'Shoppe::Customer'
    belongs_to :user, :class_name => 'Shoppe::User'
    belongs_to :payment_type, :class_name => 'Shoppe::PaymentType'
    has_many :addresses, :through => :customers, :class_name => "Shoppe::Address"

    has_many :order_purchased_items, class_name: "Shoppe::OrderPurchasedItem", foreign_key: "order_id", :dependent => :destroy
    has_many :commissions, class_name: "Shoppe::Commission", foreign_key: "order_id", :dependent => :destroy

    # Validations
    validates :token, :presence => true
    with_options :if => Proc.new { |o| !o.building? } do |order|
      order.validates :email_address, :format => {:with => /\A\b[A-Z0-9\.\_\%\-\+]+@(?:[A-Z0-9\-]+\.)+[A-Z]{2,6}\b\z/i}
    end

    # Set some defaults
    before_validation { self.token = SecureRandom.uuid  if self.token.blank? }

    scope :assigned_to, ->(user) { where(user_id: user.id) }
    scope :unassigned, -> { where(user_id: nil) }
    scope :archived, -> { where(admin_status: "archived") }
    scope :submitted, -> { where(admin_status: "submitted") }
    scope :active, -> { where("admin_status IS NULL OR admin_status <> ?", "archived") }

    # Some methods for setting the billing & delivery addresses
    attr_accessor :save_addresses, :billing_address_id, :delivery_address_id

    # The order number
    #
    # @return [String] - the order number padded with at least 5 zeros
    def number
      id ? id.to_s.rjust(6, '0') : nil
    end

    # The length of time the customer spent building the order before submitting it to us.
    # The time from first item in basket to received.
    #
    # @return [Float] - the length of time
    def build_time
      return nil if self.received_at.blank?
      self.created_at - self.received_at
    end

    # The name of the customer in the format of "Company (First Last)" or if they don't have
    # company specified, just "First Last".
    #
    # @return [String]
    def customer_name
      company.blank? ? full_name : "#{company} (#{full_name})"
    end

    # The full name of the customer created by concatinting the first & last name
    #
    # @return [String]
    def full_name
      "#{first_name} #{last_name}"
    end

    # Is this order empty? (i.e. doesn't have any items associated with it)
    #
    # @return [Boolean]
    def empty?
      order_items.empty?
    end

    # Does this order have items?
    #
    # @return [Boolean]
    def has_items?
      total_items > 0
    end

    # Return the number of items in the order?
    #
    # @return [Integer]
    def total_items
      order_items.inject(0) { |t,i| t + i.quantity }
    end

    def assigned?
      user.present?
    end

    def self.ransackable_attributes(auth_object = nil)
      ["id", "billing_postcode", "billing_address1", "billing_address2", "billing_address3", "billing_address4", "first_name", "last_name", "company", "email_address", "phone_number", "consignment_number", "status", "received_at"] + _ransackers.keys
    end

    def self.ransackable_associations(auth_object = nil)
      []
    end

    def recalculate_commission
      commissions.destroy_all

      items_to_purchased = {}.tap do |hsh|
        order_items.each do |item|
          hsh[item.id] = order_purchased_items.select{|opi| opi.purchased_item.shoppe_product_id == item.ordered_item_id}
        end
      end

      order_items.each do |item|
        if items_to_purchased[item.id].present? #both buyer and seller should get a commission
          qty_to_sell = item.quantity
          items_to_purchased[item.id].each do |purchased|
            profit = purchased.purchased_item_qty * calc_profit(item.unit_price, purchased.purchased_item.price, payment_type.try(:slug))
            process_single_commission(user, "seller", profit)
            process_single_commission(purchased.purchased_item.user, "buyer", profit)
            qty_to_sell -= purchased.purchased_item_qty
          end
          if qty_to_sell > 0
            profit = qty_to_sell * calc_profit(item.unit_price, item.unit_cost_price, payment_type.try(:slug))
            process_single_commission(user, "seller", profit)
          end
        else #only seller gets commission
          profit = item.quantity * calc_profit(item.unit_price, item.unit_cost_price, payment_type.try(:slug))
          process_single_commission(user, "seller", profit)
        end
      end
    end

    def admin_status_str
      case admin_status
      when "submitted"
        "Submitted to Admin"
      when "archived"
        "Archived by Admin"
      else
        "In Process"
      end
    end

    private

    def process_single_commission(comm_user, comm_type, profit)
      comm = commissions.where(user_id: comm_user.id, commission_type: comm_type).first_or_initialize
      comm.commission_amount = comm.commission_amount.to_f + (profit * (comm_user.send("#{comm_type}_cut") || 0) / 100.0)
      comm.save
    end

    def calc_profit(price, cost, pay_type)
      case pay_type
      when "paypal"
        return calc_paypal_profit(price, cost)
      when "skrill"
        return calc_skrill_profit(price, cost)
      else
        return calc_other_profit(price, cost)
      end
    end

    def calc_paypal_profit price, cost
      (price.to_f * 0.981) - 0.3 - (cost * 1.01)
    end

    def calc_skrill_profit price, cost
      (price.to_f * 0.951) - 0.3 - (cost * 1.01)
    end

    def calc_other_profit price, cost
      price.to_f - (cost * 1.01)
    end
  end
end

app/models/shoppe/payment_type.rb
module Shoppe
  class PaymentType < ActiveRecord::Base
    has_many :orders, :class_name => 'Shoppe::Order'
    has_many :purchased_items, :class_name => 'Shoppe::PurchasedItems'
  end
end

app/views/shoppe/customers/_addresses.html.haml
.addresses
  .table
    %table.data
      %thead
        %tr
          %th Type
          %th Default
          %th Address
          %th
      %tbody
        - if @addresses.empty?
          %tr.empty
            %td{:colspan => 4} No addresses to display.
        - else
          - for address in @addresses
            %tr
              %td= address.address_type.capitalize
              %td= boolean_tag address.default
              %td= address.full_address
              %td= link_to "Edit", edit_customer_address_path(@customer, address)

app/views/shoppe/customers/_form.html.haml
= form_for @customer do |f|
  = f.error_messages

  = field_set_tag "Customer Information" do
    .splitContainer
      %dl.third
        %dt= f.label :first_name
        %dd= f.text_field :first_name, :class => "text focus"
      %dl.third
        %dt= f.label :last_name
        %dd= f.text_field :last_name, :class => "text"
      %dl.third
        %dt= f.label :company
        %dd= f.text_field :company, :class => "text"
    .splitContainer
      %dl.third
        %dt= f.label :email
        %dd= f.text_field :email, :class => "text"
      %dl.third
        %dt= f.label :phone
        %dd= f.text_field :phone, :class => "text"
      %dl.third
        %dt= f.label :mobile
        %dd= f.text_field :mobile, :class => "text"
    %dl
      %dt= f.label :customer_identification, "Customer Identification"
      %dd= f.file_field :customer_identification

  %p.submit
    - unless @customer.new_record?
      %span.right= link_to "Delete", @customer, :class => 'button purple', :method => :delete, :data => {:confirm => "Are you sure you wish to remove this product?"}
    = f.submit :class => 'button green', data: {disable_with: (@customer.new_record? ? "Creating Customer..." : "Updating Customer...")}
    = link_to "Cancel", :customers, :class => 'button'

app/views/shoppe/customers/_search_form.html.haml
.customerSearch{:style => action_name == 'search' ? "display:block" : ''}
  = search_form_for @query, :url => search_customers_path, :html => { :method => :post } do |f|
    %dl.left
      %dt= f.label :first_name_or_last_name_or_company_cont, "First or Last Name"
      %dd= f.text_field :first_name_or_last_name_or_company_cont
      %dt= f.label :company_cont, "Company"
      %dd= f.text_field :company_cont
    %dl.right
      %dt= f.label :email_cont, "Email Address"
      %dd= f.text_field :email_cont
      %dt= f.label :phone_cont, "Phone Number"
      %dd= f.text_field :phone_cont
      %dd= f.submit "Search", :class => 'button green button'

app/views/shoppe/customers/edit.html.haml
- @page_title = "Customers"
= content_for :header do
  %p.buttons= link_to "Back to customer list", :customers, :class => 'button'
  %h2.users Customers
= render "form"

app/views/shoppe/customers/index.html.haml
- @page_title = "Customers"

= content_for :header do
  %p.buttons
    = link_to "New Customer", :new_customer, class: "button green"
    = link_to "Search Customers", '#', class: 'button', rel: "searchCustomers"
  %h2.users Customers

= render "search_form"

.table
  %table.data
    %thead
      %tr
        %th Name
        %th Company
        %th Email
        %th Phone
        %th Mobile
    %tbody
      - if @customers.empty?
        %tr.empty
          %td{colspan: 5} No customers to display.
      - else
        - for customer in @customers
          %tr
            %td= link_to customer.full_name, customer
            %td= link_to customer.company, customer
            %td= customer.email
            %td= customer.phone
            %td= customer.mobile
= paginate @customers

app/views/shoppe/customers/new.html.haml
- @page_title = "Customers"
= content_for :header do
  %p.buttons= link_to "Back to customer list", :customers, :class => 'button'
  %h2.users Customers
= render "form"

app/views/shoppe/customers/show.html.haml
- @page_title = "Customer - #{@customer.name}"
= content_for :header do
  %p.buttons
    = link_to "New Address", [:new, @customer, :address], class: "button"
    = link_to "Edit", [:edit, @customer], class: "button"
  %h2.users
    Customer - #{@customer.name}

#customer
  .details
    .left
      %dl
        %dt Name
        %dd= @customer.full_name
        %dt Company
        %dd= @customer.company.blank? ? '-' : @customer.company
        %dt= "Identification"
        %dd
          - if @customer.customer_identification.present?
            = link_to image_tag(@customer.customer_identification.url(:thumb)), @customer.customer_identification.url(), target: "_blank"
          - else
            Not provided
    .right
      %dl
        %dt Email Address
        %dd= mail_to @customer.email
        %dt Telephone
        %dd= @customer.phone
        %dt Mobile
        %dd= @customer.mobile

  = field_set_tag "Addresses", :class => 'padded' do
    = render "addresses"

  = field_set_tag t('shoppe.orders.orders'), :class => 'padded' do
    .table
      %table.data
        %thead
          %tr
            %th= t('shoppe.orders.number')
            %th= t('shoppe.orders.status')
            %th= t('shoppe.orders.products')
            %th= t('shoppe.orders.total')
            %th= t('shoppe.orders.payment')
            %th= "Payment Type"
        %tbody
          - if @orders.empty?
            %tr.empty
              %td{:colspan => 6}= t('shoppe.orders.no_orders')
          - else
            - for order in @orders
              %tr
                %td= link_to order.number, order
                %td= status_tag order.status
                %td
                  %ul
                    - for item in order.order_items
                      %li #{item.quantity} x #{item.ordered_item.full_name}
                %td= number_to_currency order.total
                %td= boolean_tag order.paid_in_full?, nil, :true_text => number_to_currency(order.amount_paid), :false_text => number_to_currency(order.amount_paid)
                %td= order.payment_type.try(:name) || "Not selected"